### ISSUE TITLE
Epic/VerifyEmailToken

### ISSUE THREAD

**Issue by kimlisa** [hwsc-org/hwsc-app-gateway-svc#34]
VerifyEmailToken service is used to verify that the user has entered a valid email address belonging to the user. It is used to validate `users creating account for first time` and `existing users wanting to update their email`.

### High level process
- User clicks on verification link from their email
- Chrome opens this link
- Chrome will validate the url to ensure proper format to prevent abuse
  - i.e: does it contain the proper stub `token=someToken`
- Chrome will extract the token string from the url
- **Chrome will send this extracted token to `gateway` using token authentication dial in the format of ` "authorization": "Email Token " + token` as metadata in the context**
- **`gateway` has to determine the token type (this is to differentiate between `VerifyEmailToken` and `VerifyAuthToken`**
- `gateway` will send this token to `user-svc` `VerifyEmailToken`
- `VerifyEmailToken` will look up token in `user_svc.email_tokens` table
 
#### If token does not exist, user-svc will:
- send back error with token does not exist
- Chrome will tell user that this link is no longer valid and user must re-sign up ~or login~

#### If token exists and is NOT expired, user-svc will:
- delete this token from `user_svc.email_tokens` table
- grab user row from `user_svc.accounts` table by looking up UUID grabbed from `user_svc.email_tokens`
- modify user column's `is_verified` to TRUE
- send this user row back with OK message

#### If token exists but is expired, user-svc will:
- delete this token from `user_svc.email_tokens` table 
- grab user row from `user_svc.accounts` table by looking up UUID grabbed from `user_svc.email_tokens` table
- generate a new email token and insert into `user_svc.email_tokens`
- resend a verification email to the email based on two criteria:
  1. resend email under `prospective_email` column if its column is not null/empty
  2. resend email under `email` column if `prospective_email` column is null/empty
- send back a message saying token has expired, and we have sent a new verification email
- is the above considered an error? or an OK with the above message?

Note: For new users, if the token existed in the table but was expired, this means that the `maintenance-svc` hasn't gotten around deleting the token and user from the database. We might as well re-use this information and allow new user to just click on a resent verification link??

**Comment by faraonc** [comment]
```
#### If token exists but is expired, user-svc will:
- delete this token from `user_svc.email_tokens` table 
- grab user row from `user_svc.accounts` table by looking up UUID grabbed from `user_svc.email_tokens` table
- generate a new email token and insert into `user_svc.email_tokens`
- resend a verification email to the email based on two criteria:
  1. resend email under `prospective_email` column if its column is not null/empty
  2. resend email under `email` column if `prospective_email` column is null/empty
- send back a message saying token has expired, and we have sent a new verification email
- is the above considered an error? or an OK with the above message?
```
**If token has expired:**
- delete this token from `user_svc.email_tokens` table
- delete the user from `user_svc.accounts` table
- the two deletions above can have collision with `maintenance-svc`, therefore we should check if they exist or not in the query.
- send back error with token does not exist
- Chrome will tell user that this link is no longer valid and user must re-sign up
